-- For PostgreSQL

CREATE TABLE person (
    person_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_name VARCHAR(100) NOT NULL,
    person_age INT CHECK( person_age > 0 ),
    person_email VARCHAR(100) NOT NULL UNIQUE,
    time_registration_person TIMESTAMP,
    person_role VARCHAR(50)
);
# --
CREATE TABLE product (
    product_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL,
    product_price INT CHECK( product_price >= 0 ),
    product_amount INT CHECK ( product_amount >= 0 )
);
# --
CREATE TABLE order_user(
    order_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id INT REFERENCES person ON DELETE CASCADE,
    time_created_order TIMESTAMP
);
# --
CREATE TABLE order_product (
    order_product_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INT REFERENCES order_user ON DELETE CASCADE ON UPDATE CASCADE,
    product_id INT REFERENCES product ON DELETE SET NULL ON UPDATE CASCADE,
    order_amount INT CHECK ( order_amount > 0 )
);
# --
CREATE TABLE basket (
    basket_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id INT REFERENCES person ON DELETE CASCADE ON UPDATE CASCADE,
    product_id INT REFERENCES product ON DELETE SET NULL ON UPDATE CASCADE,
    basket_amount INT CHECK ( basket_amount > 0 )
);
# --
INSERT INTO person (person_name, person_age, person_email)
VALUES ('Anton', 31, 'anton@mail.ru'),
       ('Gulya', 30, 'gulya@mail.ru'),
       ('Mark', 4, 'mark@gmail.com');
# --
INSERT INTO product (product_name, product_price, product_amount)
VALUES ('LEGO', 5000, 12),
       ('HotWheels', 750, 29),
       ('ТехноПарк', 600, 14),
       ('PawPatrol', 2200, 7),
       ('Пружинка', 150, 35),
       ('Мяч', 475, 15),
       ('Велосипед', 11550, 4),
       ('Barbie', 2125, 11),
       ('Kinder', 75, 62),
       ('Tetris', 575, 22),
       ('Кубик-Рубика', 400, 17),
       ('Уточка', 250, 20);
#
INSERT INTO order_user (person_id)
VALUES (1),
       (2),
       (2),
       (3);
#
INSERT INTO basket (person_id, product_id, basket_amount)
VALUES (1,3,1),
       (1,7,1),
       (1,9,1);
#
INSERT INTO order_product (order_id, product_id, order_amount)
VALUES (1,2,5),
       (1,5,2),
       (1,11,1),
       (2,5,3),
       (3,6,2),
       (4,4,4),
       (4,7,1),
       (4,10,1),
       (4,1,2);
#
